--Lab 23 Implement Stored Procedures for Reusable SQL Operations 
-- From the table STUDENT perform the following queries:  
--Part – A:  
--1. INSERT Procedures: Create stored procedures to insert records into STUDENT tables (SP_INSERT_STUDENT) 

CREATE PROC PR_INSERT_STUDENT
@STDID INT,@SNAME VARCHAR(20),@CITY VARCHAR(20),@SPI DECIMAL(4,2),@BRANCH VARCHAR(20)
AS 
BEGIN
   INSERT INTO STUDENT VALUES (@STDID ,@SNAME,@CITY ,@SPI ,@BRANCH)
END

EXEC PR_INSERT_STUDENT 115,'PUSHTI','RAJKOT',9.48,'COMPUTER'
EXEC PR_INSERT_STUDENT 116,'NIKUNJ','SURAT',8.80,'CHEMICAL' 

SELECT *FROM STUDENT

--2. INSERT Procedures: Create stored procedures to insert records into DEPOSIT tables
CREATE PROC PR_INSERT_DEPOSIT
@ACTNO INT,
@CNAME VARCHAR(50),
@BNAME VARCHAR(50),
@AMOUNT DECIMAL(8,2),
@ADATE DATETIME
AS 
BEGIN 
	INSERT INTO DEPOSIT VALUES (@ACTNO,@CNAME,@BNAME,@AMOUNT,@ADATE)
END 

EXEC PR_INSERT_DEPOSIT 118,'HEMENT','BEDI',16000,'2025-05-05'
EXEC PR_INSERT_DEPOSIT 119,'RAVI','MAVDI',24000,'2024-07-09'

SELECT *FROM DEPOSIT




--  UPDATE Procedures: Create stored procedure SP_UPDATE_STUDENT to update Branch in STUDENT table. (Update using studentID) 



CREATE PROC PR_UPDATE_STUDENT 
    @STDID  INT,
    @BRANCH VARCHAR(50)
AS
BEGIN
    UPDATE STUDENT
    SET BRANCH=@BRANCH
    WHERE STDID=@STDID
END;


EXEC PR_UPDATE_STUDENT 115, 'ELECTRICAL';
EXEC PR_UPDATE_STUDENT 116, 'MECHANICAL';


SELECT *FROM STUDENT

--4. DELETE Procedures: Create stored procedure SP_DELETE_STUDENT to delete records from STUDENT where Student Name is RAVI. 

CREATE PROC PR_DELETE_STUDENT
@SNAME VARCHAR(50)
AS
DELETE FROM STUDENT
WHERE SNAME=@SNAME

EXEC PR_DELETE_STUDENT 'RAVI'

--5. SELECT BY PRIMARY KEY: Create stored procedures to select records by primary key 
--(PR_SELECT_STUDENT_BY_ID) from Student table. (Display All Columns) 

CREATE PROCEDURE PR_SELECT_STUDENT_BY_ID
    @STDID INT 
AS
BEGIN
    SELECT *
    FROM STUDENT
    WHERE STDID = @STDID
END;


EXEC PR_SELECT_STUDENT_BY_ID 115;
    

--6. Create a stored procedure that shows details of the first 5 students ordered by SPI (Highest First). 

CREATE PROCEDURE PR_TOP_5_STUDENTS
AS
BEGIN
    SELECT TOP 5 *
    FROM STUDENT
    ORDER BY SPI DESC;
END;

EXEC PR_TOP_5_STUDENTS

--From the table EMPLOYEE perform the following queries:  
--Part – B:   
--7. Create a stored procedure which displays all employee details. 


CREATE PROCEDURE PR_SELECT_EMPLOYEE
AS
BEGIN
    SELECT *
    FROM EMPLOYEE
    
END;


EXEC PR_SELECT_EMPLOYEE 