--Copy all records from DEPOSIT where AMOUNT > 3000 into HIGH_AMOUNT.

SELECT ACTNO,CNAME,BNAME,AMOUNT,ADATE INTO HIGHT_AMOUNT
FROM DEPOSIT
WHERE AMOUNT>3000;

--Copy only CNAME and AMOUNT from DEPOSIT where BNAME = 'MAVDI' into MAVDI_CUSTOMERS.  

SELECT ACTNO,CNAME INTO MAVDI_CUSTOMERS
FROM DEPOSIT
WHERE BNAME='MAVDI';

--Copy records of DEPOSIT where ADATE > '2025-01-01' into RECENT_DEPOSITS.

SELECT ACTNO,CNAME,BNAME,AMOUNT,ADATE INTO RECENT_DEPOSITS
FROM DEPOSIT 
WHERE ADATE > '2025-01-01';

--Copy distinct BNAME from DEPOSIT into BRANCH_LIST.

SELECT DISTINCT BNAME INTO BRANCH_LIST
FROM DEPOSIT 

--Copy top 5 records from DEPOSIT into TOP_DEPOSITS. 

SELECT TOP 5 ACTNO,CNAME,BNAME,AMOUNT,ADATE INTO TOP_DEPOSITS
FROM DEPOSIT;

-- Copy records where AMOUNT between 2000 and 6000 into MID_RANGE. 

SELECT ACTNO,CNAME,BNAME,AMOUNT,ADATE INTO MID_RANGE
FROM DEPOSIT
WHERE AMOUNT BETWEEN 2000 AND 6000;

SELECT * FROM MID_RANGE

--Copy distinct branch names from DEPOSIT into UNIQUE_BRANCH. 

SELECT DISTINCT BNAME INTO UNIQUE_BRANCH
FROM DEPOSIT

--Copy records with NULL branch into NO_BRANCH_ASSIGNED.  

SELECT ACTNO,CNAME,BNAME,AMOUNT,ADATE INTO NO_BRANCH_ASSIGNED
FROM DEPOSIT
WHERE BNAME IS NULL;

--Copy all records and rename AMOUNT as BALANCE into DEPOSIT_COPY

SELECT ACTNO,CNAME,BNAME,AMOUNT AS BALANCE,ADATE INTO DEPOSIT_COPY
FROM DEPOSIT


-- Copy records where BNAME in ('MAVDI','BEDI') into SELECTED_BRANCH.  

SELECT ACTNO,CNAME,BNAME,AMOUNT,ADATE INTO SELECTED_BRANCH
FROM DEPOSIT
WHERE BNAME IN ('MAVDI','BEDI');

--Create a new table STUDENT_BACKUP from STUDENT without copying any data.

SELECT * INTO STUDENT_BACKUP 
FROM STUDENT
WHERE 1 = 2;

--Copy SNAME and CITY where BRANCH = 'COMPUTER' into CS_STUDENTS.  

SELECT SNAME,CITY INTO CS_STUDENTS
FROM STUDENT
WHERE BRANCH='COMPUTER';

-- Copy top 3 students based on SPI into TOPPER_LIST.

SELECT TOP 3 SPI INTO TOPPER_LIST
FROM STUDENT

--Copy distinct CITY from STUDENT into CITY_LIST.

SELECT DISTINCT CITY INTO CITY_LIST
FROM STUDENT;

-- Copy records where STDID between 103 and 108 into MID_STUDENTS. 

SELECT * INTO MID_STUDENTS
FROM STUDENT
WHERE STDID BETWEEN 103 AND 108;

--Copy records with NULL branch into NULL_BRANCH_STUDENTS.

SELECT * INTO NULL_BRANCH_STUDENTS
FROM STUDENT
WHERE BRANCH IS NULL;

-- Copy all STUDENT records and rename SPI as PERFORMANCE into STUDENT_COPY.  

SELECT STDID,SNAME,CITY,SPI AS PERFORMANCE,BRANCH INTO STUDENT_COPY
FROM STUDENT

-- Copy records where CITY in ('RAJKOT','SURAT') into CITY_WISE

SELECT * INTO CITY_WISE
FROM STUDENT
WHERE CITY IN ('RAJKOT','SURAT');

-- Copy students where BRANCH <> 'CIVIL' into NON_CIVIL_STUDENTS.  

SELECT * INTO NON_CIVIL_STUDENTS
FROM STUDENT
WHERE BRANCH <> 'CIVIL';

--Copy selected columns (SNAME, CITY) from STUDENT table into a new table.

SELECT SNAME,CITY INTO NEW_TABLE
FROM STUDENT;
