--Part – A: 
--1. Combine information from Person and Department table using cross join or Cartesian product

SELECT *
FROM PERSON CROSS JOIN DEPARTMENT

--2. Find all persons with their department name 

SELECT P.PERSONNAME,D.DEPARTMENTNAME 
FROM PERSON AS P JOIN DEPARTMENT AS D
ON D.DEPARTMENTID = P.DEPARTMENTID;

--3. Find all persons with their department name & code. 

SELECT P.PERSONNAME,D.DEPARTMENTNAME,D.DEPARTMENTCODE
FROM PERSON AS P JOIN DEPARTMENT AS D
ON D.DEPARTMENTID = P.DEPARTMENTID;

--4. Find all persons with their department code and location. 

SELECT D.DEPARTMENTCODE,D.LOCATION
FROM PERSON AS P JOIN DEPARTMENT AS D
ON D.DEPARTMENTID = P.DEPARTMENTID;

--5. Find the detail of the person who belongs to Mechanical department. 

SELECT P.PERSONNAME,D.DEPARTMENTNAME
FROM PERSON AS P JOIN DEPARTMENT AS D
ON D.DEPARTMENTID = P.DEPARTMENTID
WHERE D.DEPARTMENTNAME = 'MECHANICAL'


--6. Final person’s name, department code and salary who lives in Ahmedabad city. 

SELECT P.PERSONNAME,D.DEPARTMENTCODE,P.SALARY
FROM PERSON AS P JOIN DEPARTMENT AS D
ON D.DEPARTMENTID = P.DEPARTMENTID
WHERE P.CITY = 'AHMEDABAD'

--7. Find the person's name whose department is in C-Block

SELECT D.DEPARTMENTCODE,D.LOCATION
FROM PERSON AS P JOIN DEPARTMENT AS D
ON D.DEPARTMENTID = P.DEPARTMENTID
WHERE D.LOCATION = 'C-BLOCK'

--8. Retrieve person name, salary & department name who belongs to Jamnagar city.

SELECT P.PERSONNAME,P.SALARY,D.DEPARTMENTNAME
FROM PERSON AS P JOIN DEPARTMENT AS D
ON D.DEPARTMENTID = P.DEPARTMENTID
WHERE P.CITY = 'JAMNAGAR'

--9. Retrieve person’s detail who joined the Civil department after 1-Aug-2001. 

SELECT P.PERSONNAME,P.JOININGDATE
FROM PERSON AS P JOIN DEPARTMENT AS D
ON D.DEPARTMENTID = P.DEPARTMENTID
WHERE P.JOININGDATE > '1-AUG-2001'

--10. Display all the person's name with the department whose joining date difference with the current date  is more than 25 years. 

SELECT P.PERSONNAME,P.JOININGDATE
FROM PERSON AS P JOIN DEPARTMENT AS D
ON D.DEPARTMENTID = P.DEPARTMENTID
WHERE DATEDIFF(YEAR,P.JOININGDATE,GETDATE()) > 25

--11. Find department wise person counts. 

SELECT D.DEPARTMENTNAME,COUNT(*)
FROM PERSON AS P JOIN DEPARTMENT AS D
ON D.DEPARTMENTID = P.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME;

--12. Give department wise maximum & minimum salary with department name. 

SELECT D.DEPARTMENTNAME,MIN(P.SALARY) AS MIN_SALARY,MAX(P.SALARY) AS MAX_SALARY
FROM PERSON AS P JOIN DEPARTMENT AS D
ON D.DEPARTMENTID = P.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME;

--13. Find city wise total, average, maximum and minimum salary. 

SELECT P.CITY,MIN(P.SALARY) AS MIN_SALARY,MAX(P.SALARY) AS MAX_SALARY, AVG(SALARY) AS AVG_SALARY,SUM(SALARY) AS SUM_SALARY
FROM PERSON AS P JOIN DEPARTMENT AS D
ON D.DEPARTMENTID = P.DEPARTMENTID
GROUP BY P.CITY;

--14. Find the average salary of a person who belongs to Ahmedabad city.

SELECT  P.PERSONNAME,AVG(SALARY) AS AVG_SALARY
FROM PERSON AS P JOIN DEPARTMENT AS D
ON D.DEPARTMENTID = P.DEPARTMENTID
WHERE P.CITY = 'AHMEDABAD'
GROUP BY P.PERSONNAME

--15. Produce Output Like: <PersonName> lives in <City> and works in <DepartmentName> Department. (In single column) 

SELECT P.PERSONNAME + 'lives in' +  P.CITY +'works in'+ D.DEPARTMENTNAME
FROM PERSON AS P JOIN DEPARTMENT AS D
ON D.DEPARTMENTID = P.DEPARTMENTID

--Part – B: 
--16. Produce Output Like: <PersonName> earns <Salary> from <DepartmentName> department monthly. (In single column) 

SELECT P.PERSONNAME + 'EARNS' +  CAST(P.SALARY AS varchar(20)) +'FROM'+ D.DEPARTMENTNAME
FROM PERSON AS P JOIN DEPARTMENT AS D
ON D.DEPARTMENTID = P.DEPARTMENTID

--17. Find city & department wise total, average & maximum salaries. 

SELECT P.CITY,D.DEPARTMENTNAME,MAX(P.SALARY) AS MAX_SALARY, AVG(SALARY) AS AVG_SALARY,SUM(SALARY) AS SUM_SALARY
FROM PERSON AS P JOIN DEPARTMENT AS D
ON D.DEPARTMENTID = P.DEPARTMENTID
GROUP BY P.CITY,D.DEPARTMENTNAME;


--18. Find all persons who do not belong to any department.

SELECT  P.PERSONNAME
FROM PERSON AS P JOIN DEPARTMENT AS D
ON D.DEPARTMENTID = P.DEPARTMENTID
WHERE D.DEPARTMENTNAME IS NULL

--19. Find all departments whose total salary is exceeding 100000. 

SELECT D.DEPARTMENTNAME,SUM(SALARY) AS SUM_SALARY
FROM PERSON AS P JOIN DEPARTMENT AS D
ON D.DEPARTMENTID = P.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME
HAVING SUM(SALARY) > 100000;

--Part – C: 
--20. List all departments who have no person. 

SELECT  D.DEPARTMENTNAME
FROM PERSON AS P JOIN DEPARTMENT AS D
ON D.DEPARTMENTID = P.DEPARTMENTID
WHERE P.PERSONNAME IS NULL

--21. List out department names in which more than two persons are working. 

SELECT  D.DEPARTMENTNAME,COUNT(*) AS PERSONS_WORK
FROM PERSON AS P JOIN DEPARTMENT AS D
ON D.DEPARTMENTID = P.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME
HAVING COUNT(*) > 2

--22. Give a 10% increment in the computer department employee’s salary. (Use Update) 


UPDATE PERSON
SET SALARY = SALARY + (0.1*SALARY)
FROM PERSON AS P JOIN DEPARTMENT AS D
ON D.DEPARTMENTID = P.DEPARTMENTID
WHERE D.DEPARTMENTNAME = 'COMPUTER';

SELECT * FROM PERSON;
SELECT * FROM DEPARTMENT